# Generated by Django 3.0.3 on 2020-07-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_topic1', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_webpage2', models.CharField(max_length=264, unique=True)),
                ('col_webpage3', models.URLField(unique=True)),
                ('col_webpage1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.table_topic')),
            ],
        ),
        migrations.CreateModel(
            name='table_AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_AccessRecord2', models.DateField()),
                ('col_AccessRecord1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.table_webpage')),
            ],
        ),
    ]
