# Generated by Django 3.0.3 on 2020-07-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_accessrecord',
            name='col_AccessRecord1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrec', to='test_app.table_webpage'),
        ),
    ]
